<?php
/**
 * Created by PhpStorm.
 * User: lengbin
 * Date: 2016/10/31
 * Time: 11:38
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Admin extends Model{
    protected  $table = 'admin';
    public $timestamps = true;
    protected $fillable = ['username','password'];
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }
}